
import React from 'react';
import {
  Dumbbell, Heart, Brain, Wallet, Sparkles,
  Coffee, Book, Droplets, Moon, Sun,
  Music, Camera, Bike, Pizza, Timer,
  Code, Gamepad2, Languages, Palette, GraduationCap,
  Footprints, Leaf, Pill, Bed, ShowerHead,
  Utensils, Stethoscope, Plane, Car, Cloud,
  TreePine, Wine, MessageCircle, Users, Briefcase,
  Target, Zap, Flame, Trophy, Smile,
  FlaskConical, Microscope, Atom, Library, Pencil,
  Cherry, Wind, Activity, BicepsFlexed, Swords,
  Palmtree, Map, Globe, Apple, Salad
} from 'lucide-react';

export const DEFAULT_CATEGORIES = [
  { id: 'cat-sports', name: 'Sports', color: '#94A3B8' },
  { id: 'cat-health', name: 'Health', color: '#38BDF8' },
  { id: 'cat-psyche', name: 'Psyche', color: '#A5B4FC' },
  { id: 'cat-finance', name: 'Finance', color: '#6366F1' },
  { id: 'cat-interests', name: 'Interests', color: '#475569' },
];

export const ICONS = [
  { id: 'dumbbell', component: <Dumbbell /> },
  { id: 'heart', component: <Heart /> },
  { id: 'brain', component: <Brain /> },
  { id: 'wallet', component: <Wallet /> },
  { id: 'sparkles', component: <Sparkles /> },
  { id: 'coffee', component: <Coffee /> },
  { id: 'book', component: <Book /> },
  { id: 'droplets', component: <Droplets /> },
  { id: 'moon', component: <Moon /> },
  { id: 'sun', component: <Sun /> },
  { id: 'music', component: <Music /> },
  { id: 'camera', component: <Camera /> },
  { id: 'bike', component: <Bike /> },
  { id: 'pizza', component: <Pizza /> },
  { id: 'timer', component: <Timer /> },
  { id: 'code', component: <Code /> },
  { id: 'gamepad', component: <Gamepad2 /> },
  { id: 'languages', component: <Languages /> },
  { id: 'palette', component: <Palette /> },
  { id: 'graduation', component: <GraduationCap /> },
  { id: 'footprints', component: <Footprints /> },
  { id: 'leaf', component: <Leaf /> },
  { id: 'pill', component: <Pill /> },
  { id: 'bed', component: <Bed /> },
  { id: 'shower', component: <ShowerHead /> },
  { id: 'utensils', component: <Utensils /> },
  { id: 'stethoscope', component: <Stethoscope /> },
  { id: 'plane', component: <Plane /> },
  { id: 'car', component: <Car /> },
  { id: 'cloud', component: <Cloud /> },
  { id: 'tree', component: <TreePine /> },
  { id: 'wine', component: <Wine /> },
  { id: 'message', component: <MessageCircle /> },
  { id: 'users', component: <Users /> },
  { id: 'briefcase', component: <Briefcase /> },
  { id: 'target', component: <Target /> },
  { id: 'zap', component: <Zap /> },
  { id: 'flame', component: <Flame /> },
  { id: 'trophy', component: <Trophy /> },
  { id: 'smile', component: <Smile /> },
  { id: 'flask', component: <FlaskConical /> },
  { id: 'microscope', component: <Microscope /> },
  { id: 'atom', component: <Atom /> },
  { id: 'library', component: <Library /> },
  { id: 'pencil', component: <Pencil /> },
  { id: 'cherry', component: <Cherry /> },
  { id: 'wind', component: <Wind /> },
  { id: 'activity', component: <Activity /> },
  { id: 'biceps', component: <BicepsFlexed /> },
  { id: 'swords', component: <Swords /> },
  { id: 'palmtree', component: <Palmtree /> },
  { id: 'map', component: <Map /> },
  { id: 'globe', component: <Globe /> },
  { id: 'apple', component: <Apple /> },
  { id: 'salad', component: <Salad /> },
];

export const getIconById = (id: string) => {
  return ICONS.find(icon => icon.id === id)?.component || <Sparkles />;
};
